spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/profootballdraft
    username: profootball_admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
